#!/usr/bin/env python3
"""Extract distinctive per-archetype signature weights for submission inference."""

from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

from poke_agent.archetypes import load_archetype_registry  # noqa: E402

_WEIGHT_SCALE = 10_000


def _format_signatures(signatures: dict[str, dict[int, int]]) -> str:
    lines = [
        "# Auto-generated by scripts/extract_archetype_signatures.py — do not edit.",
        f"_WEIGHT_SCALE = {_WEIGHT_SCALE}",
        "VISIBLE_ARCHETYPE_SIGNATURES: dict[str, dict[int, int]] = {",
    ]
    for slug in sorted(signatures):
        card_map = signatures[slug]
        lines.append(f'    "{slug}": {{')
        for card_id, weight in sorted(card_map.items()):
            lines.append(f"        {card_id}: {weight},")
        lines.append("    },")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=ROOT / "submission" / "archetype_signatures_data.py",
        help="Python module to write signature constants into",
    )
    args = parser.parse_args()

    registry = load_archetype_registry(ROOT)
    raw = registry.distinctive_visible_signatures()
    payload = {
        slug: {card: max(1, int(round(weight * _WEIGHT_SCALE))) for card, weight in cards.items()}
        for slug, cards in raw.items()
    }
    if not payload:
        raise SystemExit("no distinctive archetype signatures extracted from competitive decks")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(_format_signatures(payload), encoding="utf-8")
    print(f"wrote {len(payload)} archetype signatures to {args.output}")
    for slug in sorted(payload)[:8]:
        print(f"  {slug}: {len(payload[slug])} distinctive cards")
    if len(payload) > 8:
        print(f"  ... and {len(payload) - 8} more")


if __name__ == "__main__":
    main()
