#!/usr/bin/env python3
"""Emit the one host-neutral r241 managed-start authorization receipt.

This is deliberately a narrow, create-only authorization step.  It does not
start a systemd unit, stage a host, touch a checkpoint, collect a game, or
submit anything.  Its only effect is to record an explicit operator decision
that a later checksum-bound activation overlay may authorize the managed r241
training service.

The generated bytes are host-neutral.  The mirror installer is responsible for
placing byte-identical copies beneath the Inzi and Elmo external output roots.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
import tempfile
from pathlib import Path
from typing import Any, Mapping, Sequence


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from poke_bot import r241_baseline_payload_snapshot as baseline_payload  # noqa: E402


SCHEMA = "poke_bot.alakazam_new_list_direct_r241_owner_start_authorization/v1"
GENERATOR_SCHEMA = (
    "poke_bot.alakazam_new_list_direct_r241_owner_start_authorization_generator/v1"
)
SOURCE_SNAPSHOT_SCHEMA = "poke_bot.alakazam_new_list_direct_r241_source_snapshot/v1"
CANDIDATE_ID = "alakazam-new-list-direct-policy-r241"
REVISION = 241
_SHA256_PREFIX = "sha256:"


class R241OwnerStartAuthorizationError(RuntimeError):
    """The explicit service-start authority cannot be safely recorded."""


def _canonical_json(value: object) -> bytes:
    try:
        return (
            json.dumps(value, sort_keys=True, separators=(",", ":"), allow_nan=False)
            + "\n"
        ).encode("utf-8")
    except (TypeError, ValueError) as exc:
        raise R241OwnerStartAuthorizationError(
            "owner-start authorization payload is not canonical JSON"
        ) from exc


def _sha256_file(path: Path | str) -> str:
    digest = hashlib.sha256()
    with Path(path).open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return _SHA256_PREFIX + digest.hexdigest()


def _valid_sha256(value: object, *, label: str) -> str:
    rendered = str(value or "")
    if not rendered.startswith(_SHA256_PREFIX) or len(rendered) != 71:
        raise R241OwnerStartAuthorizationError(f"{label} lacks a canonical SHA-256")
    try:
        int(rendered.removeprefix(_SHA256_PREFIX), 16)
    except ValueError as exc:
        raise R241OwnerStartAuthorizationError(
            f"{label} is not a hexadecimal SHA-256"
        ) from exc
    return rendered


def _regular_file(path: Path | str, *, label: str) -> Path:
    raw = Path(path).expanduser()
    if raw.is_symlink() or not raw.is_file():
        raise R241OwnerStartAuthorizationError(
            f"{label} must be a regular non-symlink file: {raw}"
        )
    return raw.resolve()


def _regular_directory(path: Path | str, *, label: str) -> Path:
    raw = Path(path).expanduser()
    if raw.is_symlink() or not raw.is_dir():
        raise R241OwnerStartAuthorizationError(
            f"{label} must be a real non-symlink directory: {raw}"
        )
    return raw.resolve()


def _read_json(path: Path | str, *, label: str) -> tuple[Path, dict[str, Any]]:
    file = _regular_file(path, label=label)
    try:
        payload = json.loads(file.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise R241OwnerStartAuthorizationError(
            f"{label} is not readable JSON: {file}"
        ) from exc
    if not isinstance(payload, dict):
        raise R241OwnerStartAuthorizationError(f"{label} must contain an object")
    return file, payload


def _mapping(value: object, *, label: str) -> dict[str, Any]:
    if not isinstance(value, Mapping):
        raise R241OwnerStartAuthorizationError(f"{label} must be an object")
    return dict(value)


def _expect_sha(path: Path | str, digest: str, *, label: str) -> Path:
    file = _regular_file(path, label=label)
    expected = _valid_sha256(digest, label=label)
    actual = _sha256_file(file)
    if actual != expected:
        raise R241OwnerStartAuthorizationError(
            f"{label} checksum mismatch: expected={expected} actual={actual}"
        )
    return file


def _create_only_json(path: Path | str, payload: Mapping[str, object]) -> Path:
    raw = Path(path).expanduser()
    if raw.is_symlink():
        raise R241OwnerStartAuthorizationError(
            f"owner-start authorization output may not be a symlink: {raw}"
        )
    parent = _regular_directory(raw.parent, label="owner-start authorization output parent")
    target = parent / raw.name
    encoded = _canonical_json(payload)
    if target.exists():
        if target.is_symlink() or not target.is_file() or target.read_bytes() != encoded:
            raise R241OwnerStartAuthorizationError(
                f"owner-start authorization output already exists with different bytes: {target}"
            )
        if target.stat().st_mode & 0o222:
            raise R241OwnerStartAuthorizationError(
                f"existing owner-start authorization output is writable: {target}"
            )
        return target.resolve()
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{target.name}.", suffix=".tmp", dir=parent
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(encoded)
            stream.flush()
            os.fsync(stream.fileno())
        temporary.chmod(0o444)
        try:
            os.link(temporary, target)
        except FileExistsError:
            if target.is_symlink() or not target.is_file() or target.read_bytes() != encoded:
                raise R241OwnerStartAuthorizationError(
                    f"owner-start authorization output already exists with different bytes: {target}"
                )
        if target.stat().st_mode & 0o222:
            raise R241OwnerStartAuthorizationError(
                f"owner-start authorization publication became writable: {target}"
            )
        return target.resolve()
    finally:
        temporary.unlink(missing_ok=True)


def _owner_contract(
    path: Path | str, *, expected_sha256: str
) -> tuple[Path, dict[str, Any], dict[str, Any]]:
    owner_path = _expect_sha(path, expected_sha256, label="r241 owner contract")
    _, owner = _read_json(owner_path, label="r241 owner contract")
    submission = _mapping(owner.get("submission"), label="r241 owner submission")
    boundary = {
        "exact_count": 1,
        "checkpoint_source": "expert_before_iter_00010.pt",
        "intermediate_iteration_5_submission_allowed": False,
        "retry_copy_or_duplicate_allowed": False,
    }
    if (
        owner.get("schema") != "poke_bot.alakazam_new_list_direct_policy_r241/v1"
        or owner.get("candidate_id") != CANDIDATE_ID
        or owner.get("latest_owner_clarification_revision") != 251
        or any(submission.get(key) != value for key, value in boundary.items())
    ):
        raise R241OwnerStartAuthorizationError(
            "owner contract does not preserve the r241 one-submit boundary"
        )
    return owner_path, owner, boundary


def _source_snapshot(
    path: Path | str,
    *,
    expected_sha256: str,
    owner_contract_sha256: str,
) -> tuple[Path, dict[str, Any]]:
    manifest_path = _expect_sha(path, expected_sha256, label="r241 source snapshot manifest")
    _, manifest = _read_json(manifest_path, label="r241 source snapshot manifest")
    files = manifest.get("files")
    if (
        manifest.get("schema") != SOURCE_SNAPSHOT_SCHEMA
        or manifest.get("candidate_id") != CANDIDATE_ID
        or manifest.get("owner_contract_sha256") != owner_contract_sha256
        or manifest.get("external_outputs_required") is not True
        or manifest.get("baseline_payloads_separate_and_receipted") is not True
        or manifest.get("authenticated") is not True
        or manifest.get("status") != "authenticated_immutable_source_snapshot"
        or not isinstance(files, list)
        or not files
    ):
        raise R241OwnerStartAuthorizationError(
            "source snapshot manifest does not bind immutable r241 intent"
        )
    _valid_sha256(manifest.get("source_tree_sha256"), label="source snapshot tree")
    return manifest_path, manifest


def stage_authorization(
    *,
    owner_contract: Path | str,
    owner_contract_sha256: str,
    source_snapshot_manifest: Path | str,
    source_snapshot_manifest_sha256: str,
    canonical_roster_receipt: Path | str,
    canonical_roster_receipt_sha256: str,
    output: Path | str,
    authorize_managed_start: bool,
) -> dict[str, object]:
    """Validate immutable inputs and write one deterministic authorization."""

    if authorize_managed_start is not True:
        raise R241OwnerStartAuthorizationError(
            "refusing to emit authority without --authorize-managed-start"
        )
    owner_sha = _valid_sha256(owner_contract_sha256, label="owner contract")
    _owner_path, _owner, submission_boundary = _owner_contract(
        owner_contract, expected_sha256=owner_sha
    )
    manifest_path, manifest = _source_snapshot(
        source_snapshot_manifest,
        expected_sha256=source_snapshot_manifest_sha256,
        owner_contract_sha256=owner_sha,
    )
    canonical_path = _expect_sha(
        canonical_roster_receipt,
        canonical_roster_receipt_sha256,
        label="canonical baseline roster receipt",
    )
    try:
        _, roster = baseline_payload.validate_canonical_roster_receipt(
            canonical_path,
            expected_sha256=canonical_roster_receipt_sha256,
            owner_contract_sha256=owner_sha,
        )
    except baseline_payload.R241BaselinePayloadError as exc:
        raise R241OwnerStartAuthorizationError(
            f"canonical baseline roster receipt failed validation: {exc}"
        ) from exc
    payload: dict[str, object] = {
        "schema": SCHEMA,
        "revision": REVISION,
        "candidate_id": CANDIDATE_ID,
        "status": "authorized",
        "authorized": True,
        "owner_contract_sha256": owner_sha,
        "allowed_actions": ["managed_r241_training_start"],
        "source_snapshot_manifest_sha256": _sha256_file(manifest_path),
        "source_tree_sha256": str(manifest["source_tree_sha256"]),
        "canonical_baseline_manifest_sha256": str(roster["baseline_manifest_sha256"]),
        "canonical_baseline_roster_sha256": str(roster["baseline_roster_sha256"]),
        "submission_boundary": submission_boundary,
        "authorization_provenance": {
            "schema": GENERATOR_SCHEMA,
            "create_only": True,
            "explicit_operator_intent": "authorize_managed_r241_training_start",
        },
    }
    emitted = _create_only_json(output, payload)
    return {
        "path": str(emitted),
        "sha256": _sha256_file(emitted),
        "payload": payload,
    }


def _parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--owner-contract", type=Path, required=True)
    parser.add_argument("--owner-contract-sha256", required=True)
    parser.add_argument("--source-snapshot-manifest", type=Path, required=True)
    parser.add_argument("--source-snapshot-manifest-sha256", required=True)
    parser.add_argument("--canonical-roster-receipt", type=Path, required=True)
    parser.add_argument("--canonical-roster-receipt-sha256", required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument(
        "--authorize-managed-start",
        action="store_true",
        help="explicit operator authorization; does not start a service",
    )
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = _parse_args(argv)
    result = stage_authorization(
        owner_contract=args.owner_contract,
        owner_contract_sha256=args.owner_contract_sha256,
        source_snapshot_manifest=args.source_snapshot_manifest,
        source_snapshot_manifest_sha256=args.source_snapshot_manifest_sha256,
        canonical_roster_receipt=args.canonical_roster_receipt,
        canonical_roster_receipt_sha256=args.canonical_roster_receipt_sha256,
        output=args.output,
        authorize_managed_start=args.authorize_managed_start,
    )
    print(json.dumps(result, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except R241OwnerStartAuthorizationError as exc:
        print(f"r241 owner-start authorization failed: {exc}", file=sys.stderr)
        raise SystemExit(78)
